# Generated by Django 3.2.5 on 2021-07-15 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0003_alter_post_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='POST_IMAGE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='post_images')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='post',
            constraint=models.UniqueConstraint(fields=('slug',), name='unique slug'),
        ),
        migrations.AddField(
            model_name='post_image',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.post'),
        ),
    ]
